language: node_js
node_js:
  - "16"
  - "17"
  - "18"

# Указывает Travis CI на то, что нужно выполнять сборку и тестирование на каждый коммит и пулл реквест
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Указывает Travis CI на список шагов для выполнения
jobs:
  include:
    - name: Run tests
      script:
        - npm start
        - npm run e2e
        - npm test

    - name: Run linter
      script:
        - commitlint --from=HEAD~1 --to=HEAD
